In [3]:
import numpy as np

In [4]:
np.__version__

'1.23.5'

In [5]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [6]:
print("%d bytes"%(z.size * z.itemsize))

40 bytes


In [11]:
z[4]=1
z

array([0., 0., 0., 0., 1.])

In [16]:
arr=np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [18]:
arr[::-1]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

In [24]:
arr=np.arange(0,9)

In [25]:
arr=arr.reshape(3,3)

In [26]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
nz=np.nonzero([0,0,0,0,0,0])
nz

(array([], dtype=int64),)

In [31]:
eye=np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.random.random((3,4,5))

array([[[0.33077466, 0.83628672, 0.7507414 , 0.47198432, 0.79924846],
        [0.23281464, 0.19291264, 0.23291187, 0.8571053 , 0.45965906],
        [0.68871644, 0.22882801, 0.1792526 , 0.04138264, 0.1374123 ],
        [0.18197996, 0.82483394, 0.54731203, 0.67145999, 0.55637455]],

       [[0.6736689 , 0.30066198, 0.26881846, 0.87897857, 0.24787661],
        [0.99027728, 0.19520789, 0.91672213, 0.68307904, 0.35880163],
        [0.58166156, 0.06803512, 0.19952613, 0.58537957, 0.39864311],
        [0.37353427, 0.00350943, 0.74540322, 0.34663165, 0.93926373]],

       [[0.7330134 , 0.13878993, 0.47922006, 0.08435581, 0.54675378],
        [0.21173132, 0.6754012 , 0.78757482, 0.62127028, 0.93679842],
        [0.77151024, 0.50982981, 0.13552425, 0.036595  , 0.64781479],
        [0.03352348, 0.35448826, 0.86236568, 0.15941645, 0.38134944]]])

In [55]:
# create 4*4 matrix with random valus and find the minimum and maximum values
a=np.random.random((4,4))
max=np.max(a)
max
#mini=np.min

0.9913949386083237

In [56]:
print(a.mean())

0.5250419419130078


In [59]:
z = np.ones((5,5))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
z=np.ones((5,5))
z=np.pad(z,pad_width=2,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
z=np.array((1,2,41,80,255))
z

array([  1,   2,  41,  80, 255])

In [70]:
maxi=np.max(z)
z=z/maxi
z

array([0.00392157, 0.00784314, 0.16078431, 0.31372549, 1.        ])

In [72]:
z1=np.ones((5,3))
z2=np.ones((3,4))
z1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
z2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
print(np.dot(z1,z2))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [79]:
z3=z1@z2
z3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
print(sum(range(5),-1))

In [84]:
z1=np.ones((5,4))
z2=np.ones((4,4))
print(sum(z1,z2))

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [86]:
z1>2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [87]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 1 4 5 6 8]


In [88]:
print(z1)
print(z2)

[1 4 8 0 6 9 9 9 5 4]
[3 4 0 4 5 6 6 8 1 2]


In [91]:
z1=np.random.randint(1,10,10)
z1

array([2, 7, 5, 4, 1, 3, 7, 8, 3, 1])

In [96]:
def generate():
  for x in range(10):
    yield x

z=np.fromiter(generate(),dtype=float,count=-1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [97]:
print(np.unique(z1))

[1 2 3 4 5 7 8]


In [103]:
z=np.random.random_sample(4)
z

array([0.50541035, 0.60024915, 0.82368155, 0.78249256])

In [106]:
z=np.arange(0.,10.)

In [107]:
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [112]:
z = np.arange(1,10)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
z[2:7:1]

array([3, 4, 5, 6, 7])

In [118]:
np.random.seed(42)

In [126]:
import time

In [129]:
a=np.random.rand(100000000)
b=np.random.rand(100000000)

tic = time.time()
c = np.dot(a,b)
toc =time.time()

print(f"{c:.3f}")
print(f"{1000*(toc-tic):.4f}")

24999341.260
119.1633
